// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'sub_list_model.mapper.dart';

@MappableClass()
class SubListModel with SubListModelMappable {
  @MappableField(key: 'sub_id')
  final String subId;
  final String name;
  @MappableField(key: 'main_list_id')
  final String mainListId;
  @MappableField(key: 'created_at')
  final DateTime createdAt;

  SubListModel({
    required this.subId,
    required this.name,
    required this.mainListId,
    required this.createdAt,
  });
}
