name: qaimati
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  supabase_flutter: ^2.9.0
  easy_localization: ^3.0.7+1
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  dart_mappable: ^4.5.0
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  firebase_core: ^3.14.0
  onesignal_flutter: ^5.3.3
  http: ^1.4.0
  flutter_svg: ^2.2.0
  flutter_launcher_icons: ^0.14.4
  fade_shimmer: ^2.4.0
  dotted_border: ^3.0.1
  flutter_native_splash: ^2.4.6
  image_picker: ^1.1.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  http_parser: ^4.1.2
  moyasar: ^2.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  dart_mappable_builder: ^4.5.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/
    - assets/svg/
    - assets/image/
    - assets/images/
  fonts:
    - family: SFArabicRounded
      fonts:
        - asset: assets/fonts/SF-Arabic-Rounded.ttf

    - family: SFCompactRounded
      fonts:
        - asset: assets/fonts/SF-Compact-Rounded-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Compact-Rounded-Bold.otf
          weight: 700
