// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'role_model.mapper.dart';

@MappableClass()
class RoleModel with RoleModelMappable {
  @MappableField(key: 'role_id')
  final String roleId;
  final String role;

  RoleModel({required this.roleId, required this.role});
}
