// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'main_list_model.mapper.dart';

@MappableClass()
class MainListModel with MainListModelMappable {
  final String id;
  final String name;
  @MappableField(key: 'created_at')
  final String createdAt;

  MainListModel({required this.id, required this.name, required this.createdAt});
}
