// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'item_model.mapper.dart';

@MappableClass()
class ItemModel with ItemModelMappable {

  @MappableField(key: 'item_id')
  final String itemId;
  final String title;
  final int quantity;
  final String status;
    @MappableField(key: 'sub_id')
  final String subId;
    @MappableField(key: 'member_id')
  final String memberId;
    @MappableField(key: 'created_at')
  final DateTime createdAt;
    @MappableField(key: 'closed_at')
  final DateTime closedAt;
  final bool important;

  ItemModel(this.closedAt, {required this.itemId, required this.title, required this.quantity, required this.status, required this.subId, required this.memberId,  required this.createdAt, required this.important});
}