// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'member_role_model.mapper.dart';

@MappableClass()
class MemberRoleModel with MemberRoleModelMappable {
  @MappableField(key: 'member_role_id')
  final String memberRoleId;
  @MappableField(key: 'member_id')
  final String memberId;
  @MappableField(key: 'role_id')
  final String roleId;
  @MappableField(key: 'assigned_at')
  final DateTime assignedAt;

  MemberRoleModel({
    required this.memberRoleId,
    required this.memberId,
    required this.roleId,
    required this.assignedAt,
  });
}
