// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'activity_model.mapper.dart';

@MappableClass()
class ActivityModel with ActivityModelMappable {
  //member_id
  @MappableField(key: 'actitvity_id')
  final String actitvityId;
    @MappableField(key: 'member_id')
  final String memberId;
  final String action;
    @MappableField(key: 'item_id')
  final String itemId;
    @MappableField(key: 'created_at')
  final DateTime createdAt;

  ActivityModel({required this.actitvityId, required this.memberId, required this.action, required this.itemId, required this.createdAt});
}
