// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'receipt_model.mapper.dart';

@MappableClass()

class ReceiptModel with ReceiptModelMappable{
    @MappableField(key: 'receipt_id')
  final String receiptId;
    @MappableField(key: 'item_id')
  final String itemId;
    @MappableField(key: 'member_id')
  final String memberId;
  final double total;
    @MappableField(key: 'receipt_image_url')
  final String receiptImageUrl;
   @MappableField(key: 'created_at')
  final DateTime createdAt;

  ReceiptModel({required this.receiptId, required this.itemId, required this.memberId, required this.total, required this.receiptImageUrl, required this.createdAt});
}