// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-VvZbHwDrhEZnplpzRVaE7kKXuFh34PY',
    appId: '1:946060192710:web:310174dd8745438fce60c7',
    messagingSenderId: '946060192710',
    projectId: 'qaimati-aca70',
    authDomain: 'qaimati-aca70.firebaseapp.com',
    storageBucket: 'qaimati-aca70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAo2agNYx2aDd6jX-k8SQWBKjX_N7XhI0',
    appId: '1:946060192710:android:290a55759f8677bfce60c7',
    messagingSenderId: '946060192710',
    projectId: 'qaimati-aca70',
    storageBucket: 'qaimati-aca70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy6hGScg4MBzHEYAEMaGzwhjcPM8nNL6k',
    appId: '1:946060192710:ios:d5f3e5646d74a46dce60c7',
    messagingSenderId: '946060192710',
    projectId: 'qaimati-aca70',
    storageBucket: 'qaimati-aca70.firebasestorage.app',
    iosBundleId: 'com.example.qaimati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy6hGScg4MBzHEYAEMaGzwhjcPM8nNL6k',
    appId: '1:946060192710:ios:d5f3e5646d74a46dce60c7',
    messagingSenderId: '946060192710',
    projectId: 'qaimati-aca70',
    storageBucket: 'qaimati-aca70.firebasestorage.app',
    iosBundleId: 'com.example.qaimati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-VvZbHwDrhEZnplpzRVaE7kKXuFh34PY',
    appId: '1:946060192710:web:bccdbd7e05809450ce60c7',
    messagingSenderId: '946060192710',
    projectId: 'qaimati-aca70',
    authDomain: 'qaimati-aca70.firebaseapp.com',
    storageBucket: 'qaimati-aca70.firebasestorage.app',
  );

}