// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'member_model.mapper.dart';

@MappableClass()


class MemberModel with MemberModelMappable{

    @MappableField(key: 'member_id')
     final String memberId;
     final String email;
     final String password;
    @MappableField(key: 'sub_list_id')
     final String subListId;
    @MappableField(key: 'created_at')
     final DateTime createdAt;

  MemberModel({required this.memberId, required this.email, required this.password, required this.subListId, required this.createdAt});
 
}