// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'notification_model.mapper.dart';

@MappableClass()
class NotificationModel with NotificationModelMappable {
  @MappableField(key: 'noti_id')
  final String notiId;
  @MappableField(key: 'member_id')
  final String memberId;
  final String title;
  final String body;
  @MappableField(key: 'is_read')
  final bool isRead;
  @MappableField(key: 'created_at')
  final DateTime createdAt;

  NotificationModel({required this.notiId, required this.memberId, required this.title, required this.body, required this.isRead, required this.createdAt});
}
